### ISSUE TITLE
UnhandledPromiseRejectionWarning leaving the server unresponsive

### ISSUE THREAD

**Issue by mnzaki** [jolocom/generic-backend#18]
```
avalon-back_1   | $ node ./build/server.js
avalon-back_1   | (node:57) UnhandledPromiseRejectionWarning: Error: Could not retrieve DID Document. request to https://ipfs.jolocom.com:443/api/v0/cat/QmU7kjWaEYjuarXXojsu8iNkVSMs8
ixgdL6sEQL9yPA3cj failed, reason: connect ECONNREFUSED 159.89.213.237:443
avalon-back_1   |     at JolocomRegistry.resolve (/usr/src/app/node_modules/jolocom-lib/js/registries/jolocomRegistry.js:95:19)
avalon-back_1   |     at process._tickCallback (internal/process/next_tick.js:68:7)
avalon-back_1   | (node:57) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block,
 or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
avalon-back_1   | (node:57) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.
js process with a non-zero exit code.
```
This was a temporary failure of the ipfs gateway (actually probably during a restart of the host)
The generic backend server does not respond to connections after this point

**Comment by mnzaki** [comment]
Closed by ce9d19ad86a7e43c82fa1d58f0725b4c839deb4b
